#
# https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=
#
unstable_features = true
blank_lines_lower_bound = 1
brace_style = "PreferSameLine"
fn_args_layout = "Compressed"
fn_call_width = 80
match_block_trailing_comma = true
max_width = 160
imports_granularity = "Module"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
struct_lit_width = 30
tab_spaces = 2
use_small_heuristics = "Max"
